Возможность использования флагов для задания базового урла. Рефакторинг.
nu-kotov/URLcompressor pull request #6
Opened 2024-12-20 17:08 UTC by nu-kotov

2024-12-23 14:59 UTC, bulbetski requested changes
Код написан хорошо, конфиг и обработчики написаны без замечаний. Стоит только поменять структуру проекта, разбив всё по пакетам

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main.go
>  package main
Пакет main должен отвечать только за запуск твоего приложения. Все остальные файлы надо раскидать по пакетам и назвать соответствующе. Вот примерная структура проекта
```
grpc-project/
├── api/
│   ├── proto/
│   │   ├── your_service.proto       # Прото-описание для gRPC сервисов
│   │   ├── another_service.proto    # Дополнительные proto-файлы
│   │   └── generate_protos.sh       # Скрипт для генерации gRPC кода
├── cmd/
│   ├── server/
│   │   └── main.go                  # Точка входа для gRPC сервера
│   ├── client/
│   │   └── main.go                  # Пример gRPC клиента для тестирования
├── config/
│   ├── config.yaml                  # Конфигурационный файл
│   └── config.go                    # Загрузчик конфигурации
├── internal/
│   ├── service/
│   │   ├── your_service.go          # Реализация бизнес-логики для gRPC сервисов
│   │   └── another_service.go       # Дополнительная бизнес-логика
│   ├── usecase/
│   │   ├── your_service_usecase.go  # Юз-кейсы для вашего сервиса
│   │   └── another_usecase.go       # Дополнительные юз-кейсы
│   ├── repository/
│   │   ├── repository.go            # Определение интерфейсов репозиториев
│   │   ├── redis_repository.go      # Реализация для Redis
│   │   └── sql_repository.go        # Реализация для SQL
│   └── models/
│       └── models.go                # Дата-модели и DTO
├── pkg/
│   ├── your_service/
│   │   ├── your_service.pb.go       # Сгенерированный gRPC-код
│   │   ├── your_service_grpc.pb.go  # Сгенерированные сервер и клиент gRPC
│   │   └── another_service.pb.go    # Сгенерированные дополнительные файлы
│   ├── logger/
│   │   └── logger.go                # Утилита для логирования
│   ├── middleware/
│   │   └── grpc_middleware.go       # Middleware для gRPC (например, логирование, аутентификация)
│   └── utils/
│       └── utils.go                 # Общие утилиты (например, валидация, хелперы)
├── scripts/
│   ├── migrate_db.sh                # Скрипты миграции базы данных
├── go.mod                           # Go module файл
├── go.sum                           # Файл блокировки зависимостей
└── README.md                        # Документация проекта
```

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main.go
> +	router.HandleFunc(`/{id:\w+}`, service.ShortURLByID)
Можно сделать примерно вот так
```
router := mux.NewRouter()
router.HandleFunc(`/`, service.CompressURLHandler).Methods("POST")
router.HandleFunc(`/{id:\w+}`, service.ShortURLByID).Methods("GET")
```

Тогда в твоих хэндлерах НЕ нужно проверять валидность метода по типу 
```
	if req.Method == http.MethodPost {
```

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main.go
> +	router.HandleFunc(`/{id:\w+}`, service.ShortURLByID)
Так же настройку и создание роутера стоит вынести в отдельный метод и файл

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main_handlers.go
> +func (srv *Service) CompressURLHandler(res http.ResponseWriter, req *http.Request) {
В названии не нужно писать, чем является метод. Можно просто CompressURL

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main_handlers.go
> +func (srv *Service) ShortURLByID(res http.ResponseWriter, req *http.Request) {
Тут происхдит какой-то редирект. Если так, то надо назвать RedirectByShortUrlID или что-то в этом духе

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main_utils.go
> +	h.Write([]byte(bytes))
Ты уже передаешь []byte в функцию, нет необходимости преобразовывать его ещё раз в []byte внутри h.Write().

2024-12-23 14:59 UTC, bulbetski commented on cmd/shortener/main_utils.go
> +	h.Write([]byte(bytes))
Хотя h.Write() всегда возвращает nil для ошибок в реализации FNV, явное игнорирование возвращаемых значений — это хорошая практика
```
	_, _ = h.Write(bytes) // Игнорируем ошибку, так как она всегда nil для FNV
```

2024-12-24 20:05 UTC, nu-kotov commented on cmd/shortener/main_utils.go
> +	h.Write([]byte(bytes))
Поправил.

2024-12-24 20:05 UTC, nu-kotov commented on cmd/shortener/main_handlers.go
> +func (srv *Service) ShortURLByID(res http.ResponseWriter, req *http.Request) {
Переименовал на RedirectByShortURLID.

2024-12-24 20:05 UTC, nu-kotov commented on cmd/shortener/main_handlers.go
> +func (srv *Service) CompressURLHandler(res http.ResponseWriter, req *http.Request) {
Поправил.

2024-12-24 20:07 UTC, nu-kotov commented on cmd/shortener/main.go
> +	router.HandleFunc(`/{id:\w+}`, service.ShortURLByID)
Вынес. Сначала еще поместил в отдельную папку server, но так падают автотесты в гите, требуется, чтобы код был прямо в cmd/shortener.

2024-12-24 20:09 UTC, nu-kotov commented on cmd/shortener/main.go
> +	router.HandleFunc(`/{id:\w+}`, service.ShortURLByID)
Метод, к сожалению приходится проверять явно в условии, потому что по условию задания требуется, чтобы на любые ошибки возвращался 400 код, а так будет 405 StatusMethodNotAllowed.

2024-12-24 20:10 UTC, nu-kotov commented on cmd/shortener/main.go
>  package main
Разбил на пакеты. Думаю, это не финальный вариант, потом унесу большую часть в internal.

2025-01-10 00:24 UTC, bulbetski approved these changes

2025-01-10 10:41 UTC, merged